**

!docker/
!docker/orbit-runtime/
!docker/orbit-runtime/Dockerfile
!docker/orbit-runtime/Dockerfile.dockerignore
!docker/orbit-runtime/entrypoint.sh

.env*
vendor/**
node_modules/**
apps/gateway/storage/app/orbit/ca/**
apps/gateway/storage/app/orbit/certs/**
apps/gateway/storage/app/orbit/keys/**
