#!/usr/bin/env php
<?php

declare(strict_types=1);

$artisan = __DIR__.'/apps/gateway/artisan';

if (! is_file($artisan)) {
    fwrite(STDERR, "Orbit gateway artisan not found at {$artisan}\n");

    exit(1);
}

if (($_SERVER['argv'][1] ?? null) === 'test') {
    $pest = __DIR__.'/bin/orbit-gateway-pest';
    $arguments = array_map('escapeshellarg', array_slice($_SERVER['argv'], 2));
    $command = escapeshellarg($pest);

    if ($arguments !== []) {
        $command .= ' '.implode(' ', $arguments);
    }

    passthru($command, $status);

    exit($status);
}

$_SERVER['argv'][0] = $artisan;

require $artisan;
