<?php

declare(strict_types=1);

namespace App\Actions\Apps;

use App\Contracts\RemoteShell;
use App\Models\App;
use RuntimeException;

final readonly class EnactAppRuntime
{
    public function __construct(
        private RemoteShell $remoteShell,
        private EnsureAppProxyRoute $ensureAppProxyRoute,
        private EnsureAppProcessRuntimeUnits $ensureAppProcessRuntimeUnits,
    ) {}

    /**
     * @return list<array<string, string>>
     */
    public function handle(App $app): array
    {
        $app->loadMissing('node');

        if ($app->node === null) {
            throw new RuntimeException("App '{$app->name}' has no owning node.");
        }

        $result = $this->remoteShell->run($app->node, sprintf(
            'test -x %1$s || command -v %2$s >/dev/null 2>&1 || command -v %3$s >/dev/null 2>&1 || command -v php-fpm >/dev/null 2>&1',
            escapeshellarg("/usr/sbin/php-fpm{$app->php_version}"),
            escapeshellarg("php-fpm{$app->php_version}"),
            escapeshellarg("php{$app->php_version}-fpm"),
        ));

        if ($result->successful()) {
            $this->remoteShell->run($app->node, $this->renderFpmPoolScript($app));

            return [
                ...$this->ensureAppProxyRoute->handle($app),
                ...$this->ensureAppProcessRuntimeUnits->handle($app),
            ];
        }

        return [[
            'code' => 'app.php_version_unavailable',
            'family' => 'app',
            'message' => "PHP {$app->php_version} FPM is not available on '{$app->node->name}'. Run doctor to converge app runtime artifacts.",
            'next_command' => 'doctor --family=app --fix',
        ]];
    }

    private function renderFpmPoolScript(App $app): string
    {
        $node = $app->node;

        if ($node === null) {
            throw new RuntimeException("App '{$app->name}' has no owning node.");
        }

        $user = $node->user ?: ($node->ssh_user ?: 'orbit');
        $home = $user === 'root' ? '/root' : "/home/{$user}";
        $dataPath = "{$home}/.config/orbit";
        $socketPath = "{$dataPath}/php/{$app->name}.sock";
        $logPath = "{$dataPath}/logs/php{$app->php_version}-{$app->name}-fpm.log";
        $poolPath = "/etc/php/{$app->php_version}/fpm/pool.d/orbit-{$app->name}.conf";
        $service = "php{$app->php_version}-fpm";
        $content = $this->poolContent($app->name, $user, $home, $socketPath, $logPath);

        return sprintf(
            <<<'SH'
sudo mkdir -p %s %s %s
cat <<'ORBIT_FPM_POOL' | sudo tee %s >/dev/null
%s
ORBIT_FPM_POOL
sudo systemctl reload %s || sudo systemctl reload php-fpm
SH,
            escapeshellarg(dirname($poolPath)),
            escapeshellarg(dirname($socketPath)),
            escapeshellarg(dirname($logPath)),
            escapeshellarg($poolPath),
            $content,
            escapeshellarg($service),
        );
    }

    private function poolContent(string $appName, string $user, string $home, string $socketPath, string $logPath): string
    {
        return <<<CONF
; Orbit Per-App PHP-FPM Pool Configuration
; Generated by Orbit -- do not edit manually

[orbit-{$appName}]
user = {$user}
group = {$user}

listen = {$socketPath}
listen.owner = {$user}
listen.group = {$user}
listen.mode = 0660

pm = ondemand
pm.max_children = 10
pm.process_idle_timeout = 10s
pm.max_requests = 500

php_admin_value[error_log] = {$logPath}
php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[HOME] = {$home}
env[USER] = {$user}
CONF;
    }
}
