<?php

declare(strict_types=1);

namespace App\Services\Workspaces;

use App\Models\Workspace;
use Illuminate\Support\Str;

final readonly class WorkspaceFpmPoolRenderer
{
    public function path(Workspace $workspace): string
    {
        return "/etc/php/{$workspace->effectivePhpVersion()}/fpm/pool.d/{$this->poolName($workspace)}.conf";
    }

    public function service(Workspace $workspace): string
    {
        return "php{$workspace->effectivePhpVersion()}-fpm";
    }

    public function poolName(Workspace $workspace): string
    {
        $workspace->loadMissing('app');

        return 'orbit-'.str($workspace->app?->name)->slug()->toString().'-'.str($workspace->name)->slug()->toString();
    }

    public function socketPath(Workspace $workspace): string
    {
        return $this->dataPath($workspace).'/php/'.$this->poolName($workspace).'.sock';
    }

    public function logPath(Workspace $workspace): string
    {
        $phpVersion = str_replace('.', '', (string) $workspace->effectivePhpVersion());

        return $this->dataPath($workspace)."/logs/php{$phpVersion}-{$this->poolName($workspace)}-fpm.log";
    }

    public function content(Workspace $workspace): string
    {
        $user = $this->runtimeUser($workspace);
        $home = $this->home($workspace);
        $socketPath = $this->socketPath($workspace);
        $logPath = $this->logPath($workspace);
        $poolName = $this->poolName($workspace);
        $envPath = "{$home}/.local/bin:{$home}/.bun/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin";
        $path = rtrim((string) $workspace->path, '/');

        return <<<CONF
; Orbit Per-Workspace PHP-FPM Pool Configuration
; Generated by Orbit -- do not edit manually

[{$poolName}]
user = {$user}
group = {$user}

listen = {$socketPath}
listen.owner = {$user}
listen.group = {$user}
listen.mode = 0660

pm = ondemand
pm.max_children = 10
pm.process_idle_timeout = 10s
pm.max_requests = 500

php_admin_value[error_log] = {$logPath}
php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no
chdir = {$path}
clear_env = yes

php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 64M
php_admin_value[post_max_size] = 64M
php_admin_value[max_execution_time] = 60
php_admin_value[open_basedir] = {$this->openBasedir($workspace)}
php_admin_value[disable_functions] = {$this->disabledFunctions()}

php_admin_flag[display_errors] = off
php_admin_flag[display_startup_errors] = off
php_admin_flag[expose_php] = off
php_admin_flag[allow_url_include] = off
php_admin_flag[session.cookie_httponly] = on
php_admin_flag[session.cookie_secure] = on
php_admin_value[session.cookie_samesite] = Lax
php_admin_flag[session.use_strict_mode] = on

env[PATH] = {$envPath}
env[HOME] = {$home}
env[USER] = {$user}
CONF;
    }

    public function runtimeUser(Workspace $workspace): string
    {
        $workspace->loadMissing('app');

        $appName = $workspace->app?->name ?: 'app';
        $slug = Str::of("{$appName}-{$workspace->name}")->slug('-')->lower()->toString();
        $slug = $slug !== '' ? $slug : 'workspace';
        $suffix = substr(hash('sha1', $slug), 0, 6);
        $base = substr($slug, 0, 16);

        return "orbit-ws-{$base}-{$suffix}";
    }

    public function openBasedir(Workspace $workspace): string
    {
        $path = rtrim((string) $workspace->path, '/');

        return implode(':', array_values(array_unique([
            $path,
            "{$path}/storage",
            "{$path}/bootstrap/cache",
            "{$path}/public/uploads",
            "{$path}/vendor",
            '/tmp',
        ])));
    }

    public function disabledFunctions(): string
    {
        return 'exec,passthru,shell_exec,system,proc_open,popen,pcntl_exec';
    }

    /**
     * @return list<string>
     */
    public function readWritePaths(Workspace $workspace): array
    {
        $path = rtrim((string) $workspace->path, '/');

        return [
            $path,
            "{$path}/storage",
            "{$path}/bootstrap/cache",
            "{$path}/public/uploads",
            $this->dataPath($workspace),
        ];
    }

    private function dataPath(Workspace $workspace): string
    {
        return $this->home($workspace).'/.config/orbit';
    }

    private function home(Workspace $workspace): string
    {
        $user = $this->runtimeUser($workspace);

        return $user === 'root' ? '/root' : "/home/{$user}";
    }
}
