<?php

declare(strict_types=1);

namespace App\Services\Workspaces;

use App\Models\Workspace;

final readonly class WorkspaceFpmPoolRenderer
{
    public function path(Workspace $workspace): string
    {
        return "/etc/php/{$workspace->effectivePhpVersion()}/fpm/pool.d/{$this->poolName($workspace)}.conf";
    }

    public function service(Workspace $workspace): string
    {
        return "php{$workspace->effectivePhpVersion()}-fpm";
    }

    public function poolName(Workspace $workspace): string
    {
        $workspace->loadMissing('app');

        return 'orbit-'.str($workspace->app?->name)->slug()->toString().'-'.str($workspace->name)->slug()->toString();
    }

    public function socketPath(Workspace $workspace): string
    {
        return $this->dataPath($workspace).'/php/'.$this->poolName($workspace).'.sock';
    }

    public function logPath(Workspace $workspace): string
    {
        $phpVersion = str_replace('.', '', (string) $workspace->effectivePhpVersion());

        return $this->dataPath($workspace)."/logs/php{$phpVersion}-{$this->poolName($workspace)}-fpm.log";
    }

    public function content(Workspace $workspace): string
    {
        $user = $this->user($workspace);
        $home = $this->home($workspace);
        $socketPath = $this->socketPath($workspace);
        $logPath = $this->logPath($workspace);
        $poolName = $this->poolName($workspace);
        $envPath = "{$home}/.local/bin:{$home}/.bun/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin";

        return <<<CONF
; Orbit Per-Workspace PHP-FPM Pool Configuration
; Generated by Orbit -- do not edit manually

[{$poolName}]
user = {$user}
group = {$user}

listen = {$socketPath}
listen.owner = {$user}
listen.group = {$user}
listen.mode = 0660

pm = ondemand
pm.max_children = 10
pm.process_idle_timeout = 10s
pm.max_requests = 500

php_admin_value[error_log] = {$logPath}
php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no

php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 64M
php_admin_value[post_max_size] = 64M
php_admin_value[max_execution_time] = 60

php_admin_flag[display_errors] = off
php_admin_flag[display_startup_errors] = off
php_admin_flag[expose_php] = off
php_admin_flag[allow_url_include] = off
php_admin_flag[session.cookie_httponly] = on
php_admin_flag[session.cookie_secure] = on
php_admin_value[session.cookie_samesite] = Lax
php_admin_flag[session.use_strict_mode] = on

env[PATH] = {$envPath}
env[HOME] = {$home}
env[USER] = {$user}
CONF;
    }

    private function dataPath(Workspace $workspace): string
    {
        return $this->home($workspace).'/.config/orbit';
    }

    private function home(Workspace $workspace): string
    {
        $user = $this->user($workspace);

        return $user === 'root' ? '/root' : "/home/{$user}";
    }

    private function user(Workspace $workspace): string
    {
        $workspace->loadMissing('app.node');

        return $workspace->app?->node?->user ?: ($workspace->app?->node?->ssh_user ?: 'orbit');
    }
}
