<?php

declare(strict_types=1);

use App\Http\Controllers\Api\ActivityListController;
use App\Http\Controllers\Api\ActivityShowController;
use App\Http\Controllers\Api\AgentIdeAdapterChoicesController;
use App\Http\Controllers\Api\AgentIdeMessageController;
use App\Http\Controllers\Api\AppAgentIdeController;
use App\Http\Controllers\Api\AppListController;
use App\Http\Controllers\Api\AppPruneController;
use App\Http\Controllers\Api\AppRegisterController;
use App\Http\Controllers\Api\AppRemoveController;
use App\Http\Controllers\Api\AppRootController;
use App\Http\Controllers\Api\AppShowController;
use App\Http\Controllers\Api\AppStoreController;
use App\Http\Controllers\Api\CaRootController;
use App\Http\Controllers\Api\DeployController;
use App\Http\Controllers\Api\DoctorRunController;
use App\Http\Controllers\Api\FirewallRuleDestroyController;
use App\Http\Controllers\Api\FirewallRuleListController;
use App\Http\Controllers\Api\FirewallRuleStoreController;
use App\Http\Controllers\Api\MeController;
use App\Http\Controllers\Api\NodeAgentIdeController;
use App\Http\Controllers\Api\NodeDefaultController;
use App\Http\Controllers\Api\NodeGrantController;
use App\Http\Controllers\Api\NodeListController;
use App\Http\Controllers\Api\NodeRemoveController;
use App\Http\Controllers\Api\NodeRevokeController;
use App\Http\Controllers\Api\NodeShowController;
use App\Http\Controllers\Api\NodeStoreController;
use App\Http\Controllers\Api\NodeUpdateController;
use App\Http\Controllers\Api\ProcessDestroyController;
use App\Http\Controllers\Api\ProcessEventIngestController;
use App\Http\Controllers\Api\ProcessListController;
use App\Http\Controllers\Api\ProcessLogController;
use App\Http\Controllers\Api\ProcessRestartController;
use App\Http\Controllers\Api\ProcessStartController;
use App\Http\Controllers\Api\ProcessStopController;
use App\Http\Controllers\Api\ProcessStoreController;
use App\Http\Controllers\Api\ProcessUpdateController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\ProxyRouteDestroyController;
use App\Http\Controllers\Api\ProxyRouteListController;
use App\Http\Controllers\Api\ProxyRouteStoreController;
use App\Http\Controllers\Api\ScheduleDestroyController;
use App\Http\Controllers\Api\ScheduleListController;
use App\Http\Controllers\Api\ScheduleLogsController;
use App\Http\Controllers\Api\SchedulerHeartbeatController;
use App\Http\Controllers\Api\ScheduleRunController;
use App\Http\Controllers\Api\ScheduleRunStoreController;
use App\Http\Controllers\Api\ScheduleShowController;
use App\Http\Controllers\Api\ScheduleStoreController;
use App\Http\Controllers\Api\ScheduleSyncController;
use App\Http\Controllers\Api\ToolCredentialsController;
use App\Http\Controllers\Api\ToolInstallController;
use App\Http\Controllers\Api\ToolListController;
use App\Http\Controllers\Api\ToolLogsController;
use App\Http\Controllers\Api\ToolLogsStreamController;
use App\Http\Controllers\Api\ToolReconfigureController;
use App\Http\Controllers\Api\ToolReloadController;
use App\Http\Controllers\Api\ToolRemoveController;
use App\Http\Controllers\Api\ToolRestartController;
use App\Http\Controllers\Api\ToolShowController;
use App\Http\Controllers\Api\ToolStartController;
use App\Http\Controllers\Api\ToolStopController;
use App\Http\Controllers\Api\ToolUpdateBulkController;
use App\Http\Controllers\Api\ToolUpdateController;
use App\Http\Controllers\Api\UpdateAllController;
use App\Http\Controllers\Api\WorkspaceHistoryController;
use App\Http\Controllers\Api\WorkspaceListController;
use App\Http\Controllers\Api\WorkspaceLogController;
use App\Http\Controllers\Api\WorkspaceRemoveController;
use App\Http\Controllers\Api\WorkspaceSetupController;
use App\Http\Controllers\Api\WorkspaceShowController;
use App\Http\Controllers\Api\WorkspaceStepDeleteController;
use App\Http\Controllers\Api\WorkspaceStepListController;
use App\Http\Controllers\Api\WorkspaceStepStoreController;
use App\Http\Controllers\Api\WorkspaceStoreController;
use App\Http\Middleware\CorrelationHeader;
use App\Http\Middleware\LogActivity;
use App\Http\Middleware\WireGuardIdentity;
use Illuminate\Support\Facades\Route;

Route::middleware(CorrelationHeader::class)->group(function (): void {
    Route::get('/ca/root', CaRootController::class);

    Route::middleware([WireGuardIdentity::class, LogActivity::class])->group(function (): void {
        Route::get('/activity', ActivityListController::class);
        Route::get('/activity/{id}', ActivityShowController::class);
        Route::get('/agent-ide/adapters', AgentIdeAdapterChoicesController::class);
        Route::post('/agent-ide/message', AgentIdeMessageController::class);
        Route::post('/doctor/run', DoctorRunController::class);
        Route::get('/deploy/history', [DeployController::class, 'history']);
        Route::get('/deploy/log/{run}', [DeployController::class, 'log']);
        Route::post('/deploy/run', [DeployController::class, 'run']);
        Route::get('/deploy/steps', [DeployController::class, 'listSteps']);
        Route::post('/deploy/steps', [DeployController::class, 'storeStep']);
        Route::delete('/deploy/steps/{step}', [DeployController::class, 'removeStep']);
        Route::get('/me', MeController::class);
        Route::post('/events/process', ProcessEventIngestController::class);
        Route::get('/firewall-rules', FirewallRuleListController::class);
        Route::post('/firewall-rules', FirewallRuleStoreController::class);
        Route::delete('/firewall-rules/{name}', FirewallRuleDestroyController::class);
        Route::get('/processes', ProcessListController::class);
        Route::post('/processes', ProcessStoreController::class);
        Route::post('/processes/restart', ProcessRestartController::class);
        Route::post('/processes/start', ProcessStartController::class);
        Route::post('/processes/stop', ProcessStopController::class);
        Route::get('/processes/{name}/log', ProcessLogController::class);
        Route::delete('/processes/{name}', ProcessDestroyController::class);
        Route::patch('/processes/{name}', ProcessUpdateController::class);
        Route::get('/profile', ProfileController::class);
        Route::get('/proxy-routes', ProxyRouteListController::class);
        Route::post('/proxy-routes', ProxyRouteStoreController::class);
        Route::delete('/proxy-routes/{domain}', ProxyRouteDestroyController::class);
        Route::get('/schedules', ScheduleListController::class);
        Route::post('/schedules', ScheduleStoreController::class);
        Route::post('/schedules/heartbeat', SchedulerHeartbeatController::class);
        Route::get('/schedules/sync', ScheduleSyncController::class);
        Route::post('/schedules/{name}/run', ScheduleRunController::class);
        Route::get('/schedules/{name}/logs', ScheduleLogsController::class);
        Route::post('/schedules/runs', ScheduleRunStoreController::class);
        Route::delete('/schedules/{name}', ScheduleDestroyController::class);
        Route::get('/schedules/{name}', ScheduleShowController::class);
        Route::get('/workspaces', WorkspaceListController::class);
        Route::post('/workspaces', WorkspaceStoreController::class);
        Route::post('/workspaces/setup', WorkspaceSetupController::class);
        Route::get('/workspaces/history/resolve-by-path', [WorkspaceHistoryController::class, 'fromPath']);
        Route::get('/workspaces/runs/{run}/log', WorkspaceLogController::class);
        Route::get('/workspaces/steps/{phase}', WorkspaceStepListController::class);
        Route::post('/workspaces/steps/{phase}', WorkspaceStepStoreController::class);
        Route::delete('/workspaces/steps/{phase}/{step}', WorkspaceStepDeleteController::class);
        Route::get('/workspaces/resolve-by-path', [WorkspaceShowController::class, 'fromPath']);
        Route::get('/workspaces/{name}/history', WorkspaceHistoryController::class);
        Route::delete('/workspaces/{name}', WorkspaceRemoveController::class);
        Route::get('/workspaces/{name}', WorkspaceShowController::class);
        Route::get('/apps', AppListController::class);
        Route::post('/apps/register', AppRegisterController::class);
        Route::post('/apps', AppStoreController::class);
        Route::post('/apps/prune', AppPruneController::class);
        Route::post('/apps/{app}/agent-ide', AppAgentIdeController::class);
        Route::post('/apps/{app}/root', AppRootController::class);
        Route::delete('/apps/{app}', AppRemoveController::class);
        Route::get('/apps/{app}', AppShowController::class);
        Route::get('/tools', ToolListController::class);
        Route::delete('/tools/{tool}', ToolRemoveController::class);
        Route::post('/tools/{tool}/install', ToolInstallController::class);
        Route::post('/tools/update', ToolUpdateBulkController::class);
        Route::post('/tools/{tool}/update', ToolUpdateController::class);
        Route::get('/tools/{tool}/credentials', ToolCredentialsController::class);
        Route::get('/tools/{tool}/logs/stream', ToolLogsStreamController::class);
        Route::get('/tools/{tool}/logs', ToolLogsController::class);
        Route::post('/tools/{tool}/reload', ToolReloadController::class);
        Route::post('/tools/{tool}/restart', ToolRestartController::class);
        Route::post('/tools/{tool}/reconfigure', ToolReconfigureController::class);
        Route::post('/tools/{tool}/start', ToolStartController::class);
        Route::post('/tools/{tool}/stop', ToolStopController::class);
        Route::get('/tools/{tool}', ToolShowController::class);
        Route::post('/update/all/stream', [UpdateAllController::class, 'stream']);
        Route::post('/update/all', UpdateAllController::class);
        Route::get('/nodes', NodeListController::class);
        Route::post('/nodes', NodeStoreController::class);
        Route::get('/nodes/default', [NodeDefaultController::class, 'show']);
        Route::put('/nodes/default', [NodeDefaultController::class, 'set']);
        Route::delete('/nodes/default', [NodeDefaultController::class, 'clear']);
        Route::post('/nodes/grant', NodeGrantController::class);
        Route::post('/nodes/revoke', NodeRevokeController::class);
        Route::post('/nodes/{name}/agent-ide', NodeAgentIdeController::class);
        Route::delete('/nodes/{name}', NodeRemoveController::class);
        Route::put('/nodes/{name}', NodeUpdateController::class);
        Route::get('/nodes/{name}', NodeShowController::class);
    });
});
