<?php

declare(strict_types=1);

$contexts = [
    'foreign_command_reference',
    'doctor_command_reference',
    'machine_handoff',
    'admin_handoff',
];

$options = [
    '--adopt',
    '--after',
    '--after-id',
    '--app',
    '--as-first-user',
    '--base',
    '--before',
    '--clear',
    '--cli',
    '--code',
    '--command',
    '--config',
    '--operator-name',
    '--correlation',
    '--crash-notification',
    '--detach',
    '--direction',
    '--doctor',
    '--domain',
    '--dry-run',
    '--environment',
    '--family',
    '--fix',
    '--follow',
    '--force',
    '--from',
    '--gateway',
    '--group',
    '--help',
    '--host',
    '--inherit',
    '--interval',
    '--json',
    '--keep-files',
    '--kind',
    '--limit',
    '--lines',
    '--live',
    '--mode',
    '--node',
    '--option',
    '--order',
    '--owner',
    '--password',
    '--path',
    '--php',
    '--php-version',
    '--port',
    '--process',
    '--protocol',
    '--proxied',
    '--public-ipv4',
    '--public-ipv6',
    '--reason',
    '--repo',
    '--reset',
    '--restart',
    '--restart-policy',
    '--restore',
    '--retention',
    '--role',
    '--root',
    '--run',
    '--script',
    '--self',
    '--since',
    '--ssh-user',
    '--start',
    '--status',
    '--step',
    '--strict',
    '--timeout',
    '--timezone',
    '--title',
    '--tld',
    '--to',
    '--totp',
    '--type',
    '--until',
    '--uri',
    '--user',
    '--version',
    '--workspace',
    '--zone',
];

return [
    'contexts' => [
        'foreign_command_reference' => [
            'markers' => ['orbit '],
        ],
        'doctor_command_reference' => [
            'markers' => ['doctor '],
        ],
        'machine_handoff' => [
            'markers' => ['next_command'],
        ],
        'admin_handoff' => [
            'markers' => ['Ask your admin to run'],
        ],
    ],
    'options' => array_fill_keys(
        $options,
        [
            'allowed_contexts' => $contexts,
            'allowed_command_families' => ['node', 'app', 'workspace', 'process'],
        ],
    ),
];
