<?php

declare(strict_types=1);

namespace App\Services\Apps;

use App\Models\App;
use App\Models\Node;
use Illuminate\Support\Str;

final readonly class AppFpmPoolRenderer
{
    public function path(App $app): string
    {
        return "/etc/php/{$app->php_version}/fpm/pool.d/orbit-{$app->name}.conf";
    }

    public function service(App $app): string
    {
        return "php{$app->php_version}-fpm";
    }

    public function socketPath(App $app): string
    {
        return $this->dataPath($app)."/php/{$app->name}.sock";
    }

    public function logPath(App $app): string
    {
        return $this->dataPath($app)."/logs/php{$app->php_version}-{$app->name}-fpm.log";
    }

    public function content(App $app): string
    {
        $user = $this->runtimeUser($app);
        $home = $this->home($app);
        $socketPath = $this->socketPath($app);
        $logPath = $this->logPath($app);
        $path = rtrim((string) $app->path, '/');

        $common = <<<CONF
; Orbit Per-App PHP-FPM Pool Configuration
; Generated by Orbit -- do not edit manually

[orbit-{$app->name}]
user = {$user}
group = {$user}

listen = {$socketPath}
listen.owner = {$user}
listen.group = caddy
listen.mode = 0660

pm = ondemand
pm.max_children = 10
pm.process_idle_timeout = 10s
pm.max_requests = 500

php_admin_value[error_log] = {$logPath}
php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no
CONF;

        if ($this->isProduction($app)) {
            return $common.PHP_EOL.PHP_EOL.<<<CONF
chdir = {$path}
clear_env = yes
php_admin_value[open_basedir] = {$this->openBasedir($app)}
php_admin_value[disable_functions] = {$this->disabledFunctions()}

CONF;
        }

        return $common.PHP_EOL.PHP_EOL.<<<CONF
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[HOME] = {$home}
env[USER] = {$user}
CONF;
    }

    public function runtimeUser(App $app): string
    {
        if (! $this->isProduction($app)) {
            $app->loadMissing('node');

            return $app->node?->user ?: 'orbit';
        }

        return $this->safeRuntimeUser($app->name);
    }

    public function openBasedir(App $app): string
    {
        $path = rtrim((string) $app->path, '/');

        return implode(':', array_values(array_unique([
            $path,
            "{$path}/storage",
            "{$path}/bootstrap/cache",
            "{$path}/public/uploads",
            "{$path}/vendor",
            '/tmp',
        ])));
    }

    public function disabledFunctions(): string
    {
        return 'exec,passthru,shell_exec,system,proc_open,popen,pcntl_exec';
    }

    /**
     * @return list<string>
     */
    public function readWritePaths(App $app): array
    {
        $path = rtrim((string) $app->path, '/');

        return [
            $path,
            "{$path}/storage",
            "{$path}/bootstrap/cache",
            "{$path}/public/uploads",
            $this->dataPath($app),
        ];
    }

    private function dataPath(App $app): string
    {
        return $this->home($app).'/.config/orbit';
    }

    private function home(App $app): string
    {
        $user = $this->runtimeUser($app);

        return $user === 'root' ? '/root' : "/home/{$user}";
    }

    private function isProduction(App $app): bool
    {
        $app->loadMissing('node');

        if ($app->environment === 'production') {
            return true;
        }

        return $app->node instanceof Node
            && $app->node->environment === 'production';
    }

    private function safeRuntimeUser(string $name): string
    {
        $slug = Str::of($name)->slug('-')->lower()->toString();
        $slug = $slug !== '' ? $slug : 'app';
        $suffix = substr(hash('sha1', $slug), 0, 6);
        $base = substr($slug, 0, 18);

        return "orbit-{$base}-{$suffix}";
    }
}
