<?php

declare(strict_types=1);

namespace App\Services\Apps;

use App\Models\App;

final readonly class AppFpmPoolRenderer
{
    public function path(App $app): string
    {
        return "/etc/php/{$app->php_version}/fpm/pool.d/orbit-{$app->name}.conf";
    }

    public function service(App $app): string
    {
        return "php{$app->php_version}-fpm";
    }

    public function socketPath(App $app): string
    {
        return $this->dataPath($app)."/php/{$app->name}.sock";
    }

    public function logPath(App $app): string
    {
        return $this->dataPath($app)."/logs/php{$app->php_version}-{$app->name}-fpm.log";
    }

    public function content(App $app): string
    {
        $user = $this->user($app);
        $home = $this->home($app);
        $socketPath = $this->socketPath($app);
        $logPath = $this->logPath($app);

        return <<<CONF
; Orbit Per-App PHP-FPM Pool Configuration
; Generated by Orbit -- do not edit manually

[orbit-{$app->name}]
user = {$user}
group = {$user}

listen = {$socketPath}
listen.owner = {$user}
listen.group = {$user}
listen.mode = 0660

pm = ondemand
pm.max_children = 10
pm.process_idle_timeout = 10s
pm.max_requests = 500

php_admin_value[error_log] = {$logPath}
php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[HOME] = {$home}
env[USER] = {$user}
CONF;
    }

    private function dataPath(App $app): string
    {
        return $this->home($app).'/.config/orbit';
    }

    private function home(App $app): string
    {
        $user = $this->user($app);

        return $user === 'root' ? '/root' : "/home/{$user}";
    }

    private function user(App $app): string
    {
        $app->loadMissing('node');

        return $app->node?->user ?: ($app->node?->ssh_user ?: 'orbit');
    }
}
