**

!apps/
!apps/reverb/
!apps/reverb/**

**/.env
**/.env.*
**/vendor
**/vendor/**
**/node_modules
**/node_modules/**
**/tests
**/tests/**
**/build
**/build/**
**/builds
**/builds/**
.git
.git/**
apps/reverb/bootstrap/cache
apps/reverb/bootstrap/cache/**
apps/reverb/storage/logs
apps/reverb/storage/logs/**
apps/reverb/storage/framework
apps/reverb/storage/framework/**
