name: Verify Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for build workflow to complete
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Waiting for build workflow to upload assets for ${TAG_NAME}..."
          
          # Wait up to 5 minutes (30 attempts x 10 seconds) for assets to appear
          MAX_ATTEMPTS=30
          ATTEMPT=0
          
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            ATTEMPT=$((ATTEMPT + 1))
            echo "Attempt ${ATTEMPT}/${MAX_ATTEMPTS}: Checking for orbit.phar..."
            
            RELEASE_JSON=$(gh api repos/${{ github.repository }}/releases/tags/${TAG_NAME} 2>/dev/null || echo '{}')
            PHAR_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name=="orbit.phar") | .browser_download_url' 2>/dev/null || echo "")
            
            if [ -n "$PHAR_URL" ] && [ "$PHAR_URL" != "null" ]; then
              echo "Found orbit.phar asset!"
              break
            fi
            
            if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
              echo "Asset not yet available. Waiting 10 seconds..."
              sleep 10
            fi
          done

      - name: Verify release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=${{ github.event.release.id }}
          TAG_NAME=${{ github.event.release.tag_name }}

          echo "Verifying release assets for ${TAG_NAME} (${RELEASE_ID})..."

          RELEASE_JSON=$(gh api repos/${{ github.repository }}/releases/${RELEASE_ID})

          # Accept both v-prefixed (v0.1.38) and plain semver (0.1.38) tags
          if [[ ! "$TAG_NAME" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::error::Release tag must be a valid semver (e.g. v0.1.34 or 0.1.34)."
            gh api repos/${{ github.repository }}/releases/${RELEASE_ID} -X PATCH -f draft=true
            exit 1
          fi

          PHAR_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name=="orbit.phar") | .browser_download_url')

          if [ -z "$PHAR_URL" ] || [ "$PHAR_URL" = "null" ]; then
            echo "::error::Could not find orbit.phar in the release assets."
            echo "Marking release as draft to prevent broken upgrades."
            gh api repos/${{ github.repository }}/releases/${RELEASE_ID} -X PATCH -f draft=true
            exit 1
          fi

          HTTP_CODE=$(curl -sL -o /dev/null -w "%{http_code}" "$PHAR_URL")
          if [ "$HTTP_CODE" != "200" ]; then
            echo "::error::orbit.phar download failed with HTTP $HTTP_CODE"
            echo "Marking release as draft to prevent broken upgrades."
            gh api repos/${{ github.repository }}/releases/${RELEASE_ID} -X PATCH -f draft=true
            exit 1
          fi

          echo "Release verification passed."
